"""Centralized theme palette – single source of truth for all UI colours."""

from __future__ import annotations


def get_palette(mode: str) -> dict[str, object]:
    """Return colour tokens for the given *mode* ('light' or 'dark')."""
    if mode == "dark":
        return {
            "primary":            "#1E3A6A",
            "hover":              "#2A4E85",
            "accent":             "#4F86E8",
            "bg":                 "#111827",
            "card":               "#1F2937",
            "card_inner":         "#243044",
            "border":             "#374151",
            "text":               "#E5E7EB",
            "text_secondary":     "#94A3B8",
            "input_bg":           "#1A2537",
            "list_bg":            "#1A2537",
            "list_text":          "#E5E7EB",
            "list_selected_bg":   "#4F86E8",
            "list_selected_text": "#FFFFFF",
            "combo_button":       "#475569",
            "combo_button_hover": "#64748B",
            "sidebar_bg":         "#162033",
            "sidebar_text":       "#CBD5E1",
            "sidebar_selected":   "#2060C8",
            "header_bg":          "#1E3A6A",
            "header_text":        "#FFFFFF",
            "card_border":        "#374151",
            "card_shadow":        "#0B1220",
            "input_border_focus": "#4C8DFF",
            "input_placeholder":  "#94A3B8",
            "btn_primary_bg":     "#2F7BFF",
            "btn_primary_hover":  "#2567D6",
            "btn_primary_text":   "#FFFFFF",
            "btn_outline_bg":     "#1F2937",
            "btn_outline_border": "#4B5563",
            "btn_outline_text":   "#E5E7EB",
            "btn_soft_bg":        "#1E293B",
            "btn_soft_text_blue": "#93C5FD",
            "btn_soft_bg_purple": "#2A1D47",
            "btn_soft_text_purple":"#C4B5FD",
            "btn_danger_bg":      "#3A1D1D",
            "btn_danger_border":  "#7F1D1D",
            "btn_danger_text":    "#FCA5A5",
            "base_font_family":   "Segoe UI",
            "title_font_family":  "Segoe UI Semibold",
        }
    return {
        "primary":            "#2F5FA9",
        "hover":              "#3B73C6",
        "accent":             "#4F86E8",
        "bg":                 "#F6F8FC",
        "card":               "#FFFFFF",
        "card_inner":         "#FFFFFF",
        "border":             "#D7DEEE",
        "text":               "#1F2A44",
        "text_secondary":     "#8A97B2",
        "input_bg":           "#FFFFFF",
        "list_bg":            "#F6F8FC",
        "list_text":          "#1F2A44",
        "list_selected_bg":   "#4F86E8",
        "list_selected_text": "#FFFFFF",
        "combo_button":       "#D7DEEE",
        "combo_button_hover": "#C5D2EA",
        "sidebar_bg":         "#2F5FA9",
        "sidebar_text":       "#DCE7FF",
        "sidebar_selected":   "#3B73C6",
        "header_bg":          "#2F5FA9",
        "header_text":        "#FFFFFF",
        "card_border":        "#E6EBF5",
        "card_shadow":        "#E9EEF9",
        "card_radius":        16,
        "input_border_focus": "#4C8DFF",
        "input_placeholder":  "#8A97B2",
        "input_radius":       10,
        "btn_primary_bg":     "#2F7BFF",
        "btn_primary_hover":  "#2567D6",
        "btn_primary_text":   "#FFFFFF",
        "btn_outline_bg":     "#FFFFFF",
        "btn_outline_border": "#D7DEEE",
        "btn_outline_text":   "#1F2A44",
        "btn_soft_bg":        "#EEF4FF",
        "btn_soft_text_blue": "#2F7BFF",
        "btn_soft_bg_purple": "#F3EFFF",
        "btn_soft_text_purple":"#7B4CFF",
        "btn_danger_bg":      "#FFF1F1",
        "btn_danger_border":  "#FFD0D0",
        "btn_danger_text":    "#E05252",
        "panel_bg":           "#FFFFFF",
        "panel_row_bg":       "#FFFFFF",
        "panel_row_selected": "#EEF4FF",
        "base_font_family":   "Segoe UI",
        "title_font_family":  "Segoe UI Semibold",
    }
